export const FILTERED_PRODUCTS_REQUEST = "FILTERED_PRODUCTS_REQUEST";
export const FILTERED_PRODUCTS_SUCCESS = "FILTERED_PRODUCTS_SUCCESS";
export const FILTERED_PRODUCTS_FAIL = "FILTERED_PRODUCTS_FAIL";

export const LOAD_PRODUCTS = "LOAD_PRODUCTS";

export const LIST_VIEW = "LIST_VIEW";
export const GRID_VIEW = "GRID_VIEW";

export const UPDATE_SORT = "UPDATE_SORT";
export const SORT_PRODUCTS = "SORT_PRODUCTS";

export const UPDATE_FILTERS = "UPDATE_FILTERS";
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";
export const CLEAR_FILTERS = "CLEAR_FILTERS";
